### Get All Categories
GET http://localhost:3000/api/categories
X-API-Key: RAHASIA
Accept: application/json

### Create New Category
POST http://localhost:3000/api/categories
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "name": "Komputer"
}

### Get Category By ID
GET http://localhost:3000/api/categories/1
X-API-Key: RAHASIA
Accept: application/json

### Update Category By ID
PUT http://localhost:3000/api/categories/2
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "name": "Angkot"
}

### Delete Category By ID
DELETE http://localhost:3000/api/categories/2
X-API-Key: RAHASIA
Accept: application/json